# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'dashboard_permissions',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCredentials',
            fields=[
                ('employee_credentials_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('secure', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee_credentials',
            },
        ),
        migrations.CreateModel(
            name='InventoryPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'inventory_permissions',
            },
        ),
        migrations.CreateModel(
            name='MasterDataPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.BooleanField(default=False, null=True)),
                ('supplier', models.BooleanField(default=False, null=True)),
                ('shop', models.BooleanField(default=False, null=True)),
                ('customer', models.BooleanField(default=False, null=True)),
                ('employee', models.BooleanField(default=False, null=True)),
                ('creating', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'master_data_permissions',
            },
        ),
        migrations.CreateModel(
            name='PrinterTemplatesPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('printer_templates', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'printer_templates_permissions',
            },
        ),
        migrations.CreateModel(
            name='PurchasePermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_list', models.BooleanField(default=False, null=True)),
                ('return_purchase', models.BooleanField(default=False, null=True)),
                ('stock', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'purchase_permissions',
            },
        ),
        migrations.CreateModel(
            name='QuotationsPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('quotations', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'quotations_permissions',
            },
        ),
        migrations.CreateModel(
            name='ReportsPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('general', models.BooleanField(default=False, null=True)),
                ('overview', models.BooleanField(default=False, null=True)),
                ('administration', models.BooleanField(default=False, null=True)),
                ('day_book', models.BooleanField(default=False, null=True)),
                ('gst', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'reports_permissions',
            },
        ),
        migrations.CreateModel(
            name='SalesPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos', models.BooleanField(default=False, null=True)),
                ('return_item', models.BooleanField(default=False, null=True)),
                ('bill_history', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'sales_permissions',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=20, unique=True)),
                ('alternate_mobile_number', models.CharField(default='', max_length=20, unique=True)),
                ('dob', models.DateField(default='')),
                ('shop_access', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_change_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
                ('employee_code', models.CharField(default='', max_length=10, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('token_key', models.TextField(default='')),
                ('profile_photo_url', models.CharField(default=None, max_length=200, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('otp', models.IntegerField(default=0, null=True)),
                ('otp_expiry', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.address')),
                ('dashboard_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.dashboardpermission')),
                ('employee_credentials_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employeecredentials')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
