# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='organisation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='employees',
            name='inventory_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.inventorypermission'),
        ),
        migrations.AddField(
            model_name='employees',
            name='master_data_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.masterdatapermission'),
        ),
        migrations.AddField(
            model_name='employees',
            name='printer_templates_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.printertemplatespermission'),
        ),
        migrations.AddField(
            model_name='employees',
            name='purchase_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.purchasepermission'),
        ),
        migrations.AddField(
            model_name='employees',
            name='quotations_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.quotationspermission'),
        ),
        migrations.AddField(
            model_name='employees',
            name='reports_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.reportspermission'),
        ),
        migrations.AddField(
            model_name='employees',
            name='sales_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.salespermission'),
        ),
    ]
