# Generated by Django 5.1.4 on 2026-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='shop_access',
            field=models.JSONField(default=list),
        ),
    ]
