# Generated by Django 5.1.4 on 2026-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employees_shop_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
