# Generated by Django 5.1.4 on 2026-09-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employees_alternate_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'dispatch_permissions',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='dispatch_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.dispatchpermission'),
        ),
    ]
