# must be unique in a given SonarQube instance
sonar.projectKey=erp_backend

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=biller_apps
sonar.exclusions=biller_apps/**/migrations/**,biller_apps/**/tests.py
#sonar.inclusion
sonar.language=py
sonar.plugins.downloadOnlyRequired=true
#sonar.python.coverage.reportPaths=coverage.xml
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8