# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_active_change_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobile_number', models.CharField(default='', max_length=20, unique=True)),
                ('id_number', models.CharField(default=None, max_length=100, null=True)),
                ('id_type', models.CharField(default=None, max_length=100, null=True)),
                ('email_id', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('customer_code', models.CharField(default='', max_length=10, unique=True)),
                ('photo_url', models.CharField(default=None, max_length=350, null=True)),
                ('id_proof_url', models.CharField(default=None, max_length=350, null=True)),
                ('occupation', models.CharField(default=None, max_length=100, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('gender', models.CharField(default=None, max_length=1, null=True)),
                ('martial_status', models.CharField(default=None, max_length=100, null=True)),
                ('religion', models.CharField(default=None, max_length=100, null=True)),
                ('blood_group', models.CharField(default=None, max_length=100, null=True)),
                ('education', models.CharField(default=None, max_length=100, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.address')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
