# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organisation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
    ]
