# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(default='', max_length=15, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('customer_billing', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.customerbills')),
            ],
            options={
                'db_table': 'pos',
            },
        ),
    ]
