# Generated by Django 5.1.4 on 2026-08-17 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employees_alternate_mobile_number'),
        ('organisation', '0002_organisation_is_active'),
        ('pos', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='customer_billing',
        ),
        migrations.AddField(
            model_name='pos',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='pos',
            name='customer_quotation_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pos',
            name='discounts_unit',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='pos',
            name='organisation_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='pos',
            name='pos_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='shop_id',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='shops.shops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent_to_customer', 'Sent to Customer'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('executed', 'Executed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='pos',
            name='wave_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pos',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pos',
            name='payment_type',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.CreateModel(
            name='POSItem',
            fields=[
                ('pos_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.items')),
                ('pos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.pos')),
            ],
            options={
                'db_table': 'pos_item',
            },
        ),
    ]
