# Generated by Django 5.1.4 on 2026-09-02 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_dispatchpermission_employees_dispatch_permission'),
        ('pos', '0002_remove_pos_customer_billing_pos_billed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='dispatch_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='dispatch_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employees'),
        ),
        migrations.AddField(
            model_name='pos',
            name='inventory_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='inventory_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent_to_customer', 'Sent to Customer'), ('confirmed', 'Confirmed'), ('inventory_pending', 'Inventory Pending'), ('inventory_confirmed', 'Inventory Confirmed'), ('dispatch_pending', 'Dispatch Pending'), ('dispatch_confirmed', 'Dispatch Confirmed'), ('ready_for_execution', 'Ready for Execution'), ('cancelled', 'Cancelled'), ('executed', 'Executed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='POSDispatch',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('logistics_company', models.CharField(default='', max_length=100)),
                ('logistics_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employees')),
                ('pos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_details', to='pos.pos')),
            ],
            options={
                'db_table': 'pos_dispatch',
            },
        ),
    ]
