# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_change_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobile_number', models.CharField(default='', max_length=20, unique=True)),
                ('alt_mobile_number', models.CharField(default='', max_length=20, null=True)),
                ('id_number', models.CharField(default='', max_length=100)),
                ('id_type', models.CharField(default='', max_length=100)),
                ('gst_number', models.CharField(default='', max_length=100)),
                ('email_id', models.EmailField(default='', max_length=254, unique=True)),
                ('supplier_code', models.CharField(default='', max_length=10, unique=True)),
                ('photo_url', models.CharField(default=None, max_length=200, null=True)),
                ('id_proof_url', models.CharField(default=None, max_length=200, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.address')),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
