# Generated by Django 5.1.4 on 2025-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_from', models.EmailField(default='', max_length=30)),
                ('url_name', models.CharField(default='', max_length=100)),
                ('request_method', models.CharField(default='', max_length=100)),
                ('payload', models.TextField(default='')),
                ('approval_code', models.CharField(default='', max_length=10, unique=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approved_time', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
    ]
