# Generated by Django 5.1.4 on 2025-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default='', max_length=100, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('progress', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
