# Generated by Django 5.1.4 on 2025-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('category_code', models.CharField(default='', max_length=50, unique=True)),
                ('secure', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
