# Generated by Django 5.0.2 on 2024-03-06 13:26

from django.db import migrations, models

from biller_apps.common.models.adress import Address



def create_initial_value(apps, schema_editor):
    Address().create(state="Kerala", country="India", street="Chalakudy")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default=None, max_length=100, null=True)),
                ('country', models.CharField(default=None, max_length=100, null=True)),
                ('street', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.RunPython(create_initial_value)
    ]
