# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=350)),
                ('code', models.CharField(default='', max_length=100, unique=True)),
                ('hsn_code', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('item_code', models.CharField(default='', max_length=10, unique=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.TextField(default='', null=True)),
                ('brand_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='brand.brand')),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='category.category')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
