# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_initial'),
        ('supplier', '0001_initial'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='supplier_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='items',
            name='tax_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='taxes.taxes'),
        ),
    ]
