# Generated by Django 5.1.4 on 2026-08-04 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_initial'),
        ('taxes', '0002_taxes_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='hsn_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taxes.taxes'),
        ),
    ]
