# Generated by Django 5.1.4 on 2026-08-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_is_active'),
        ('item', '0004_alter_items_hsn_code_alter_items_tax_code'),
        ('supplier', '0002_alter_supplier_is_active'),
        ('taxes', '0002_taxes_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='items',
            name='supplier_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.taxes'),
        ),
    ]
