# Generated by Django 5.1.4 on 2026-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_items_category_id_alter_items_supplier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='moq',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='items',
            name='no_of_packets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='items',
            name='plain_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='items',
            name='printed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='items',
            name='sku_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
