# Generated by Django 5.1.4 on 2026-08-07 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_items_moq_items_no_of_packets_items_plain_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_key', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('attribute_unit', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='item.items')),
            ],
            options={
                'db_table': 'item_attributes',
            },
        ),
        migrations.CreateModel(
            name='ItemOtherImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='item.items')),
            ],
            options={
                'db_table': 'item_other_images',
            },
        ),
    ]
