# Generated by Django 5.1.4 on 2026-08-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_itemattribute_itemotherimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
