# Generated by Django 5.1.4 on 2026-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemotherimage',
            name='image_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='items/others/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='items/images/'),
        ),
    ]
