# Generated by Django 5.1.4 on 2026-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_itemotherimage_image_url_alter_items_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemotherimage',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='image_url',
            field=models.TextField(default='', null=True),
        ),
    ]
