# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admin_report',
            },
        ),
    ]
