# Generated by Django 5.1.4 on 2026-08-17 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employees_alternate_mobile_number'),
        ('organisation', '0002_organisation_is_active'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuotation',
            fields=[
                ('customer_quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_quotation_code', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('phone_confirmed', 'Phone Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('converted', 'Converted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employees')),
                ('shop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shops')),
            ],
            options={
                'db_table': 'customer_quotation',
            },
        ),
        migrations.CreateModel(
            name='CustomerQuotationItem',
            fields=[
                ('customer_quotation_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('customer_quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_quotation.customerquotation')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.items')),
            ],
            options={
                'db_table': 'customer_quotation_item',
            },
        ),
    ]
