# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'billing',
            },
        ),
        migrations.CreateModel(
            name='CustomerBills',
            fields=[
                ('customer_bills_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discounts', models.FloatField(default=0)),
                ('discounts_unit', models.CharField(default='percentage', max_length=20)),
                ('wave_off', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'customer_bills',
            },
        ),
    ]
