# Generated by Django 5.1.4 on 2026-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbills',
            name='pos_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
