# Generated by Django 5.1.4 on 2026-09-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customerbills_pos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbills',
            name='logistics_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
