# Generated by Django 5.1.4 on 2026-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_customerbills_logistics_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbills',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customerbills',
            name='customer_phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
