# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(default='', max_length=200)),
                ('uploaded_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
    ]
