# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_code', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('total_tax', models.FloatField(default=0.0)),
                ('tax_splits', models.JSONField(default=dict)),
                ('secure', models.BooleanField(default=False)),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
    ]
