# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_initial'),
        ('organisation', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_code', models.CharField(default='', max_length=10, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('transfer_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('requested_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('destination_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_shop', to='shops.shops')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.items')),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('source_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_shop', to='shops.shops')),
            ],
            options={
                'db_table': 'stock_transfer',
            },
        ),
    ]
