# Generated by Django 5.1.4 on 2026-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
