# Generated by Django 5.1.4 on 2025-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='', max_length=100)),
                ('states', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'states',
            },
        ),
    ]
