# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_initial'),
        ('item', '0002_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_code', models.CharField(default='', max_length=10, unique=True)),
                ('return_reason', models.TextField(blank=True, default='', null=True)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='billing.billing')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.items')),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
            options={
                'db_table': 'return_item',
            },
        ),
    ]
