# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_change_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_code', models.CharField(default='', max_length=10)),
                ('website', models.TextField(default=None, null=True)),
                ('email_id', models.CharField(default=None, max_length=50, null=True)),
                ('mobile_number', models.CharField(default=None, max_length=20, null=True)),
                ('alt_mobile_number', models.CharField(default=None, max_length=20, null=True)),
                ('type', models.CharField(default='branch', max_length=100)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.address')),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
            options={
                'db_table': 'shops',
            },
        ),
    ]
