# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True, help_text='Base URL for downloading versions', null=True)),
                ('file_name', models.CharField(blank=True, help_text='Name of the installer file', max_length=255, null=True)),
                ('minimum_version', models.JSONField(help_text='Minimum required version details')),
                ('latest_stable_version', models.JSONField(help_text='Latest stable version details')),
                ('previous_stable_version', models.JSONField(help_text='Previous stable version details')),
                ('beta_version', models.JSONField(blank=True, help_text='Beta version details', null=True)),
                ('other_versions', models.JSONField(blank=True, help_text='List of other versions', null=True)),
                ('changes_in_latest_stable', models.JSONField(help_text='List of changes in the latest stable version')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the version was created')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('owner_name', models.CharField(default='', max_length=100)),
                ('owner_mobile', models.CharField(default='', max_length=20)),
                ('owner_alternate_mobile', models.CharField(default='', max_length=20)),
                ('owner_email', models.CharField(default='', max_length=30)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_count', models.IntegerField(default=0)),
                ('employee_count', models.IntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
                ('plan', models.CharField(default='CUSTOM', max_length=100)),
                ('plan_expiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_gateway', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.address')),
            ],
            options={
                'db_table': 'organisation',
            },
        ),
    ]
