# Generated by Django 5.1.4 on 2025-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'general_report',
            },
        ),
    ]
