# Generated by Django 5.1.4 on 2025-12-01 13:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSplit',
            fields=[
                ('branch_split_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'branch_split',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('buying_price', models.FloatField(default=0)),
                ('landing_cost', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('quantity_unit', models.CharField(default='Kg', max_length=10)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2025, 12, 1, 13, 45, 13, 818568, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseBills',
            fields=[
                ('purchase_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_code', models.CharField(default='', max_length=10, unique=True)),
                ('purchase_bill_number', models.CharField(default='', max_length=100)),
                ('bill_amount', models.FloatField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'purchase_bills',
            },
        ),
    ]
