# Generated by Django 5.1.4 on 2026-07-08 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 8, 8, 36, 6, 266474, tzinfo=datetime.timezone.utc)),
        ),
    ]
