# Generated by Django 5.1.4 on 2026-07-30 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 30, 12, 5, 28, 326358, tzinfo=datetime.timezone.utc)),
        ),
    ]
