# Generated by Django 5.1.4 on 2026-07-31 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 31, 10, 15, 11, 338506, tzinfo=datetime.timezone.utc)),
        ),
    ]
