# Generated by Django 5.1.4 on 2026-08-02 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 2, 16, 43, 48, 561430, tzinfo=datetime.timezone.utc)),
        ),
    ]
