# Generated by Django 5.1.4 on 2026-08-04 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 4, 5, 45, 15, 164068, tzinfo=datetime.timezone.utc)),
        ),
    ]
