# Generated by Django 5.1.4 on 2026-08-04 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 4, 6, 15, 41, 161859, tzinfo=datetime.timezone.utc)),
        ),
    ]
