# Generated by Django 5.1.4 on 2026-08-06 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 6, 5, 44, 13, 173957, tzinfo=datetime.timezone.utc)),
        ),
    ]
