# Generated by Django 5.1.4 on 2026-08-07 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 7, 17, 31, 54, 435520, tzinfo=datetime.timezone.utc)),
        ),
    ]
