# Generated by Django 5.1.4 on 2026-08-08 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 8, 9, 42, 7, 23914, tzinfo=datetime.timezone.utc)),
        ),
    ]
