# Generated by Django 5.1.4 on 2026-08-08 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 8, 13, 46, 40, 283905, tzinfo=datetime.timezone.utc)),
        ),
    ]
