# Generated by Django 5.1.4 on 2026-08-11 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 11, 16, 4, 15, 269446, tzinfo=datetime.timezone.utc)),
        ),
    ]
