# Generated by Django 5.1.4 on 2026-08-11 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 11, 17, 33, 33, 287528, tzinfo=datetime.timezone.utc)),
        ),
    ]
