# Generated by Django 5.1.4 on 2026-08-17 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 17, 9, 10, 11, 167910, tzinfo=datetime.timezone.utc)),
        ),
    ]
