# Generated by Django 5.1.4 on 2026-08-24 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_alter_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 24, 7, 24, 20, 899279, tzinfo=datetime.timezone.utc)),
        ),
    ]
