# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('quotation_code', models.CharField(default='', max_length=15, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('brand', models.CharField(default='', max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('purchase', models.BooleanField(default=False)),
                ('sales', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.items')),
                ('organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
            options={
                'db_table': 'quotation',
            },
        ),
    ]
