# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_qty', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
