# Generated by Django 5.1.4 on 2025-12-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.shops'),
        ),
    ]
