# Generated by Django 5.1.4 on 2026-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='store_mapping',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
