# Generated by Django 5.1.4 on 2026-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_store_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
