# Generated by Django 5.1.4 on 2026-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
