# Generated by Django 5.1.4 on 2026-08-11 16:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_inventory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_code', models.CharField(blank=True, max_length=25, null=True)),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eventtype', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('BULK_CREATE', 'Bulk Create'), ('BULK_UPDATE', 'Bulk Update')], max_length=20)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
            ],
            options={
                'db_table': 'inventory_logs',
                'indexes': [models.Index(fields=['batch_id'], name='inventory_l_batch_i_26e64b_idx'), models.Index(fields=['inventory_code'], name='inventory_l_invento_edddf8_idx')],
            },
        ),
    ]
