# Generated by Django 5.1.4 on 2026-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorylog_bill_number_alter_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='eventtype',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('BULK_CREATE', 'Bulk Create'), ('BULK_UPDATE', 'Bulk Update'), ('SALE_DEDUCT', 'Sale Deduct'), ('SALE_REVERSAL', 'Sale Reversal')], max_length=20),
        ),
    ]
